### ISSUE TITLE
Make Grabber Arm

### ISSUE THREAD

**Issue by rkeen9** [uvic-auvic/Mechanical-Team#10]

**Comment by bobcatCA** [comment]
Terry to spend this week coming up with claw/grabber arm concepts
-Tailor to picking up the "bottles" and moving the lid handle (pincer concept)
-Possibly re-use part of the tri-grabber arm

**Comment by bobcatCA** [comment]
-Reverse engineer grabber head
-Make new CAD model for logging 3-claw design
-Make a few concepts for addressing bottle orientation
