### ISSUE TITLE
Sub servicing apparatus

### ISSUE THREAD

**Issue by struaneamer** [uvic-auvic/Mechanical-Team#2]
Need an apparatus to allow servicing of the sub bottom face

**Comment by bobcatCA** [comment]
All 4 of the MECH team members to think of their best design concepts and a rough bill of materials by Feb 18th meeting. Needs to:
-Support the weight of the sub (90 lbs) and allow people to work on the lower surface without removing the thrusters and lifting it over.

**Comment by bobcatCA** [comment]
Chop up and re-assemble A frame
talk to Summer about machining tabs
get T-supports fabricated

**Comment by bobcatCA** [comment]
Finished A-frame. Complete attachment points for next week.
