### ISSUE TITLE
Dynamic Ballast 

### ISSUE THREAD

**Issue by rkeen9** [uvic-auvic/Mechanical-Team#20]

**Comment by bobcatCA** [comment]
[buoyancy_calculator.xlsx](https://github.com/uvic-auvic/Mechanical-Team/files/3683918/buoyancy_calculator.xlsx)
[dynamic_ballast_first_thoughts.docx](https://github.com/uvic-auvic/Mechanical-Team/files/3683919/dynamic_ballast_first_thoughts.docx)

**Comment by bobcatCA** [comment]
Just did some calc's and theory. Will be a matter of determining how much up/down net force required and how to operate it/fit it into the new sub design.
