### ISSUE TITLE
Test Torpedoes 

### ISSUE THREAD

**Issue by rkeen9** [uvic-auvic/Mechanical-Team#9]
First: remove one of the torpedos from the submarine.
second: find a bicycle pump to borrow to measure air pressure. then proceed to fire them in the fish tank.

**Comment by anijjar** [comment]
## update
I brought a bike pump from my home and the torpedos have been removed. the pump requires car to activate however. so we should get a car adapter to wall plugin or something. we can test in the fish tank for now.
